version: '2.2'
services:
  server:
    build:
      context: .
    depends_on:
      mysql:
        condition: service_started
      migration:
        condition: service_started
    ports:
    - 8080:8080
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=pass
      - MYSQL_HOST=prpcl_mysql_1
      - MYSQL_PORT=3306
      - MYSQL_DB=prophet
    networks:
    - prpcl-net
  migration:
    restart: always
    depends_on:
      mysql:
        condition: service_started
    build:
      context: .
      dockerfile: Dockerfile-migration
    environment:
      - MYSQL_USER=root
      - MYSQL_PASS=pass
      - MYSQL_HOST=prpcl_mysql_1
      - MYSQL_PORT=3306
      - MYSQL_DB=prophet
    networks:
    - prpcl-net
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=prophet
    networks:
    - prpcl-net
networks:
  prpcl-net:
